config/routes.rb
  Rails.application.routes.draw do
  devise_for :customers
resources :charges, only: [:new, :create]

  devise_for :customers, skip: :all

  get 'cartstuff/thecart'

  get '/gamepage', to: 'gamepage#show', as: 'gamepage'

  get 'products/index'

  get '', to:'homepage#index', as:'homepage'

  get 'search', to: 'gamepage#search', as: 'search'
  
  get 'search_results', to: 'gamepage#search_results', as: 'search_results'
  
  get 'category/:id', to: 'gamepage#catsearch', as: 'Category'

  get 'prod_display/:id', to: 'gamepage#prod_display', as: 'product'

  get 'most_recent', to: 'gamepage#most_recent', as: 'most_recent'
  
  get 'onsale', to: 'gamepage#onsale', as: 'onsale' 

  post 'cartstuff/:id', to: 'cartstuff#thecart', as: 'cartstuff'

  get 'carstuff', to: 'cartstuff#show', as: 'show'
  get 'checkout', to: 'cartstuff#checkout', as: 'checkout'

  post 'cartremove/remove/:id', to: 'cartstuff#remove', as: 'remove'




  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_many :feedbacks
 
 has_many :orders
 belongs_to :province
 validates :name, :last_name, :address, :city, :country, :email, :postal_code, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
 belongs_to :Customer
 validates :title, :description, presence:true
end

app/models/information.rb
class Information < ApplicationRecord
	validates :about, :description, :email, :location, presence: true
end

app/models/lineitem.rb
class Lineitem < ApplicationRecord
 belongs_to :order

 validates :name, :price, :order_id, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer
	has_many :lineitems
	validates :status, :pst_rate, :gst_rate, :customer_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord

belongs_to :category

mount_uploader :image, ImageUploader
validates :name, :description, :price, :stock_quantity, :released, presence: true

end

app/models/province.rb
class Province < ApplicationRecord
	has_many :customers
	validates :name, :pst, :gst, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :last_name, :address, :city, :country, :email, :postal_code, :province_id])
  end

end

app/controllers/cartstuff_controller.rb
class CartstuffController < ApplicationController
  before_action :initialize_session

  def thecart
  	@id = params[:id].to_i
  	@quantity = params[:quantity].to_i


  	# session[:cart] << @id unless session[:cart].include?(@id)
  	if session[:bagg].any? {|a| a['id'] == @id}
	   	session[:bagg].each do |variable|
	  		if variable['id'] == @id
	  			variable['quantity'] = @quantity	
	  		end
	  	end
	else
	  		   session[:bagg] << {:id => @id, :quantity => @quantity}
	  		
	  	
   end

	  		   redirect_to :action => :show
  	
  end

  def show
  	@products_all  = Product.all
  	@products = session[:bagg]	
 
    
  end

  def initialize_session
  	session[:bagg] ||= []
  end

  def remove
  	@id = params[:id].to_i

  	if session[:bagg].any? {|val| val['id'] == @id}

  	session[:bagg].each do |remove_item|

  	if remove_item['id'] == @id
  		session[:bagg].delete(remove_item)
  	end

	end
  end
  redirect_to :action => :show
end

def checkout
  if customer_signed_in?

    @curent_cust = current_customer
    
    @custdetails = Customer.where('id LIKE ?', @curent_cust.id).first

    @provincedetails = Province.where('id LIKE ?', @custdetails.province_id).first

    @mygst = @provincedetails.gst 
    @mypst = @provincedetails.pst

    @total_final = session[:total]
    
    @products = session[:bagg]  
    @products_all  = Product.all

    @calc_gst = @mygst * @total_final.to_f
    @calc_pst = @mypst  * @total_final.to_f
    @all_total = @total_final.to_f + @calc_pst   + @calc_gst  


  else
    redirect_to customer_session_path
  end
end
end	

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  	@grand_total = session[:grand_total]
  @amount = @grand_total.to_f
  end

  def create
    @curent_cust = current_customer
    
    @custdetails = Customer.where('id LIKE ?', @curent_cust.id).first

    @provincedetails = Province.where('id LIKE ?', @custdetails.province_id).first

    @mygst = @provincedetails.gst 
    @mypst = @provincedetails.pst

    @total_final = session[:total]

    
    @products = session[:bagg]  
    @products_all  = Product.all



    @calc_gst = @mygst * @total_final.to_f
    @calc_pst = @mypst  * @total_final.to_f
    @all_total = @total_final.to_f + @calc_pst   + @calc_gst  
  	# Amount in cents
  object1 = Order.create(:status => "Paid", :pst_rate =>@calc_pst , :gst_rate => @calc_gst, :customer_id => @curent_cust.id)
  object1.save

  @products.each do |variable|
    @products_all.each do |product|
      if variable['id'] == product.id
        object2 = Lineitem.create(:name => product.name, :price => product.price, :order_id => object1.id)
        object2.save
      end
    end
  end



  @grand_total = session[:grand_total]
  @amount = @grand_total.to_f

  @customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  @charge = Stripe::Charge.create(
    :customer    => @customer.id,
    :amount      => @amount.to_i,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )



rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
  end
end

app/controllers/gamepage_controller.rb
class GamepageController < ApplicationController
  def show
  	@products = Product.order("name").page(params[:page]).per(2)

  end

  def search
  end
  
  def search_results
  	
  	searchkeyword = params[:search_keywords]
     if params[:category_id] == ''
      @found_products = Product.where("name LIKE  '%#{searchkeyword}%'")

    else
  	@found_products = Product.where("name LIKE '%#{searchkeyword}%'").where("category_id = ?",params[:category_id])
      end
  	@cat = Category.all;
  end

  def catsearch
    # @category = Category.find(params[:id])
  	@products = Product.where(category_id: params[:id])
  end

  def prod_display
  	# @products = Product.find(params[:name])
  	@product = Product.where(id: params[:id])
  end

  def most_recent
  	@recent = Product.order(created_at: :desc)
  end

  def onsale
  	@sale = Product.where("price < ?", 50)
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  	@info = Information.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartstuff_helper.rb
module CartstuffHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gamepage_helper.rb
module GamepageHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cartstuff/checkout.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Checkout</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/portfolio-item.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Electronic Games Gallery</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" >
                <%= link_to 'HomePage',homepage_path %>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link"> 
              <%= link_to 'Games Page',gamepage_path %>
              </a>
            </li>
            
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="col-md-4">
          <h3 class="my-3">Cart Checkout</h3>
           <% @products.each do |pro| %>
 	 <% @products_all.each do |product| %>
	 <% if pro['id'] == product.id %>
 	 	<div class="products">
 		<h2> <%= product.name %></h2>
 		<p>Quantity: <%= pro['quantity'] %></p>
 		<hr>
 		<% end %>
 		<% end%>
 		<%end%>
          <p>PST: $<%= @calc_pst%></p>
          <p>GST: $<%= @calc_gst%></p>
          <p>Grand Total: $<%= @all_total%></p> 
          <% session[:grand_total] = @all_total %> 
          
          <%= form_tag new_charge_path , method: 'get' do %>
		<%= submit_tag "Proceed with payment!" %>
 	 <% end %>

      </div>
      <!-- /.row -->

      
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/cartstuff/show.html.erb

 <!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cart</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/portfolio-item.css" rel="stylesheet">
     <%= render partial: 'common/header' %>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Cart</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Portfolio Item Heading -->
      <h1 class="my-4">Items
        
      </h1>

      <!-- Portfolio Item Row -->
      <div class="row">


        <div class="col-md-4">
          <% @products.each do |pro| %>
 	 <% @products_all.each do |product| %>
	 <% if pro['id'] == product.id %>
 	 	<div class="products">
 		<h2> <%= product.name %></h2>
 		<p>Quantity: <%= pro['quantity'] %></p>
 		<p>Price: $<%= product.price %></p>
 		<p>Date released: <%= product.released %></p>
 		<p> Subtotal: $<%= pro['quantity'] * product.price %></p>
  		
  		<%= form_tag remove_path(id: product.id), method: 'post' do %>
		<%= submit_tag "Remove" %>	
 	 <% end %>
 	 
</div>
<% end %>
 	<% end %>
 <% end %>

      </div>
      
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/cartstuff/thecart.html.erb
<%= debug session[:bagg] %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong> $<%= @amount.to_f %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount:  <%= @amount.to_f %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @amount.to_f * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/gamepage/catsearch.html.erb

<!DOCTYPE html>
<html lang="en">

  <head>
  <%= render partial: 'common/header' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Category Results</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/portfolio-item.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Category Results</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>

    <div class="category">
	<% Category.all.each do |category| %>
	<li> <%= link_to category.name, Category_path(category) %></li>
		
	<% end %>

</div>


<% @products.each do |product| %>
<div class="products">
	<h2> <%= product.name %></h2>
	<p><%= image_tag product.image %></p>
	<p><%= product.description %></p>
	<p>Price: $<%= product.price %></p>
	<p>Stock: <%= product.stock_quantity %></p>
	<p>Date released: <%= product.released %></p>

	
	</div>
<% end %>

      </div>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MyProject 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>






app/views/gamepage/most_recent.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
  <%= render partial: 'common/header' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Most Recent</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/portfolio-item.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Recently updated games</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="col-md-4">
          <% @recent.each do |product| %>
		<div class="products">
		<h2> <%= link_to product.name, product_path(product)  %></h2>
		<p><%= image_tag product.image %></p>
		<p><%= product.description %></p>
		<p>Price: $<%= product.price %></p>
		<p>Stock: <%= product.stock_quantity %></p>
		<p>Date released: <%= product.released %></p>

	
		</div>
<% end %>

      </div>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MyProject 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>




app/views/gamepage/onsale.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
  	<%= render partial: 'common/header' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>On Sale</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/portfolio-item.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">On Sale</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

       <% @sale.each do |product| %>
<div class="products">
	<h2> <%= link_to product.name, product_path(product)  %></h2>
	<p><%= image_tag product.image %></p>
	<p><%= product.description %></p>
	<p>Price: $<%= product.price %></p>
	<p>Stock: <%= product.stock_quantity %></p>
	<p>Date released: <%= product.released %></p>

	
</div>
<% end %>

      </div>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MyProject 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>




app/views/gamepage/prod_display.html.erb
<h1>Games</h1>
 
 <%= render partial: 'common/header' %>


<% @product.each do |product| %>
<div class="products">
	<h2> <%= product.name %></h2>
	<p><%= image_tag product.image %></p>
	<p><%= product.description %></p>
	<p>Price: $<%= product.price %></p>
	<p>Stock: <%= product.stock_quantity %></p>
	<p>Date released: <%= product.released %></p>
	
	<%= form_tag cartstuff_path(id: product.id), method: 'post' do %>
		<p>Quantity: <%= text_field_tag "quantity" %></p>
		<%= submit_tag "Add to cart" %>
		
	<% end %>
	</div>
<% end %>


app/views/gamepage/search.html.erb
<br>
<%= link_to 'HomePage',homepage_path %>
 <%= link_to 'Games Page',gamepage_path %>
 <br>
 <h1>Search Form</h1>

<%= form_tag search_results_path, method: 'get' do %>
  <%= text_field_tag :search_keywords %>
  <%= submit_tag "Search" %>
<% end %>

app/views/gamepage/show.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portfolio Item - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/portfolio-item.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Games</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
      </div>
    </nav>

    <%= render partial: 'common/header' %>

    <!-- Page Content -->
    <div class="container">

      <h2>Search Form</h2>


<%= form_tag search_results_path, method: 'get' do %>
  <%= text_field_tag :search_keywords %>

<%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name"), include_blank: "All"%>

  <%= submit_tag "Search" %>
<% end %>
	
<div class="category">
	<% Category.all.each do |category| %>
	<li> <%= link_to category.name, Category_path(category) %></li>
		
	<% end %>

</div>


<% @products.each do |product| %>
<div class="products">
	<h2> <%= link_to product.name, product_path(product)  %></h2>
	<p><%= image_tag product.image %></p>
	<!-- <p><%= product.description %></p>
	<p>Price: $<%= product.price %></p>
	<p>Stock: <%= product.stock_quantity %></p>
	<p>Date released: <%= product.released %></p> -->

	
	</div>
<% end %>
<%= paginate @products %>


    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/homepage/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>EG Games</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/portfolio-item.css" rel="stylesheet">

  </head>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Electronic Games Gallery</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button> 
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          <a> <% if customer_signed_in? %>
              <p>Hi, <%= current_customer.name %></p>
              <%= link_to 'Log out', destroy_customer_session_path , :method => 'delete' %>
              <% else %>
            
              <%= link_to 'Sign in',customer_session_path %>

              <% end %>
          </a>
            <li class="nav-item active">
              <a class="nav-link" >
                <%= link_to 'HomePage',homepage_path %>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link"> 
              <%= link_to 'Games Page',gamepage_path %>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Portfolio Item Heading -->
      <h1 class="my-4">Electronic Games Gallery
        <small>(EG Games)</small>
      </h1>

      <!-- Portfolio Item Row -->
      <div class="row">

        <div class="col-md-8">
         <div >
	<%= image_tag("homepage/ps4.jpg") %>
	<%= image_tag("homepage/Xbox.jpg") %>
	<%= image_tag("homepage/nintendo.jpg") %>
</div> 	
        </div>

        <div class="col-md-4">
          <h3 class="my-3">About Us</h3>
          <p>
<% @info.each do |information| %>
<div class ="display">
	<h1><%= information.about %></h1>
	<p><h2>Description: </h2><%= information.description %></p>
	<p>Email: <%= information.email %></p>	
	<p>Location: <%= information.location %></p>
</div>
	
<% end %>
        </div>

      </div>
      <!-- /.row -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MyProject 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>